import java.util.Date
pipeline {
    // 1. AGENT: dove viene eseguita la pipeline
    //    'any' = usa qualsiasi agent disponibile
    //    puoi anche specificare: agent { label 'linux' } o agent { docker 'node:18' }
    agent { 
        label 'podman-agent-01' 
        } 

    // 2. ENVIRONMENT: variabili disponibili in tutta la pipeline
    //    withCredentials recupera le credenziali salvate in Jenkins
    environment {
        DOCKER_IMAGE   = "fabioviscusi/hello-world"
        DOCKER_TAG     = "${BUILD_NUMBER}"   // variabile Jenkins automatica
        REGISTRY_CREDS = credentials('dockerhub-credentials')  // ID credenziale Jenkins
    }
    stages {
        stage('Checking Date'){
            steps {
                script {
                    def date = new Date()
                    sh "echo $date"
                    if (date.getDay() == 0 || date.getDay() == 6) {
                    error "Can't build during Week-end!"
                    }
                }
            }
        }
        stage('Check for tag') {
            steps {
                script {
                    def isTag = sh(script: 'git describe --tags --exact-match HEAD', returnStatus: true) == 0
                    if (isTag) {
                        def tag = sh(script: 'git describe --tags --exact-match HEAD', returnStdout: true).trim()
                        echo "Siamo sul tag: ${tag}"
                    } else {
                        echo "Non c'è alcun tag"
                    }
                }
            }
        }
        stage('Debug variabili Git') {
            steps {
                sh 'echo "GIT_BRANCH = $GIT_BRANCH"'
                sh 'echo "GIT_COMMIT = $GIT_COMMIT"'
                sh 'git describe --tags --exact-match HEAD || echo "HEAD non corrisponde a nessun tag"'
            }
        }
        stage('Build Image') {
            steps {
                sh "podman rm -f hell-world"
                sh "podman ps -a && echo Podman è pronto per la build!"
                sh "podman build -t ${DOCKER_IMAGE}:${DOCKER_TAG} flask-app-example-build/"
                sh "podman tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest"
            }
        }
        stage('Push to DockerHub') {
            steps {
                sh "podman login docker.io -u ${REGISTRY_CREDS_USR} --password-stdin <<< ${REGISTRY_CREDS_PSW}"
                sh "podman push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                sh "podman push ${DOCKER_IMAGE}:latest"
            }
        }
        stage('Run Podman in Podman') {
            steps {
                sh "podman run -d --name hell-world -p 8000:8000 docker.io/fabioviscusi/hello-world:latest"
            }
        }
    }
    post {
        always {
            sh "podman logout docker.io"
            sh "podman rmi ${DOCKER_IMAGE}:${DOCKER_TAG} || true"  // pulizia immagini locali
           }
        success {
            echo "Build e push completati: ${DOCKER_IMAGE}:${DOCKER_TAG}"
        }
        failure {
            echo "Pipeline fallita. Controlla i log sopra."
        }
    }
}